# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package designs::Tool::OligoTm;
use base qw(Exporter);
use base qw(DynaLoader);
package designs::Tool::OligoTmc;
bootstrap designs::Tool::OligoTm;
package designs::Tool::OligoTm;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package designs::Tool::OligoTm;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package designs::Tool::OligoTm;

*end_oligodg = *designs::Tool::OligoTmc::end_oligodg;
*long_seq_tm = *designs::Tool::OligoTmc::long_seq_tm;
*oligotm = *designs::Tool::OligoTmc::oligotm;
*seqtm = *designs::Tool::OligoTmc::seqtm;
*oligodg = *designs::Tool::OligoTmc::oligodg;
*symmetry = *designs::Tool::OligoTmc::symmetry;
*divalent_to_monovalent = *designs::Tool::OligoTmc::divalent_to_monovalent;

# ------- VARIABLE STUBS --------

package designs::Tool::OligoTm;

*_OLIGO_TM = *designs::Tool::OligoTmc::_OLIGO_TM;
*OLIGOTM_ERROR = *designs::Tool::OligoTmc::OLIGOTM_ERROR;
*TM_METHOD_SANTALUCIA = *designs::Tool::OligoTmc::TM_METHOD_SANTALUCIA;
*TM_METHOD_BRESLAUER = *designs::Tool::OligoTmc::TM_METHOD_BRESLAUER;
*SALT_CORRECTION_SCHILDKRAUT = *designs::Tool::OligoTmc::SALT_CORRECTION_SCHILDKRAUT;
*SALT_CORRECTION_SANTALUCIA = *designs::Tool::OligoTmc::SALT_CORRECTION_SANTALUCIA;
*SALT_CORRECTION_OWCZARZY = *designs::Tool::OligoTmc::SALT_CORRECTION_OWCZARZY;
1;
