
---
- hosts: portal-bio-info-udes
  sudo: yes
  gather_facts: no

  handlers:

    - name: restart apache
      service: name=apache2 state=restarted

  vars:
    varDir: /var/bio-info
    dataDir: "{{varDir}}/data"
    codeDir: "{{'/vagrant' if isVagrant else '/var/bio-info/code'}}"

  tasks:

  - debug: var=codeDir

  - name: ensure Vagrant is a sudoer
    copy: content="vagrant ALL=(ALL) NOPASSWD:ALL" dest=/etc/sudoers.d/vagrant owner=root group=root
    when: isVagrant
    sudo: yes

  - name: update apt repo
    action: apt update-cache=yes cache_valid_time=86400

  - name: ensure apt cache is up to date
    apt: update_cache=yes cache_valid_time=86400

  - name: ensure data dir exists
    file: path={{varDir}} state=directory

  - name: ensure var dir exists
    file: path={{dataDir}} state=directory

  - name: install apt packages
    apt: pkg={{item}} state=latest
    with_items:
     - python-pycurl
     - swig
     - cpanminus
     - apache2
     - emboss-explorer
     - libapache2-mod-perl2


#  - name: installer les dépendances Perl
#    cpanm:  name={{item}} notest=True
#    sudo: yes
#    with_items:
#      - DBIx::Class::Schema
#      - Config::Record
#      - Data::Dump #(gentoo: see bug #189865)
#      - File::Temp
#      - Storable
#      - Term::ANSIColor
#      - Error
#      - Text::Wrap
#      - List::Util
#      - Bio::Tools::Primer3
#      - Bio::SearchIO

  - name: install unafold
    unarchive: src=../code/designs/Tool/unafold/unafold-3.8.tar.gz dest={{varDir}}

  - name: build and install unafold
    shell: "if [ ! -e {{varDir}}/unafold-3.8/config.status ]; then cd {{varDir}}/unafold-3.8 && ./configure && make && make install; fi"

  - name: install blast+ blast
    apt: pkg={{item}} state=latest
    with_items:
     - ncbi-blast+
     - blast2

  - name: fetch les BDs blast
    get_url: url="http://www.ncbi.nlm.nih.gov/sviewer/viewer.cgi?tool=portal&sendto=on&log=seqview&db=nuccore&dopt=fasta&sort=&val=NC_000913.3&from=begin&to=end" dest={{dataDir}}/NC_000913.fa

  - name: formater les BDs blast
    shell: "cd {{dataDir}} && formatdb -i {{item}} -p F"
    with_items:
     - NC_000913.fa

  - name: disable apache default site
    file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

  - name: enable apache mod cgi
    file: src=/etc/apache2/mods-available/cgi.load dest=/etc/apache2/mods-enabled/cgi.load owner=root group=root state=link

  - name: resolve apache conf for this site
    template: src=templates/apache.conf dest=/etc/apache2/sites-available/udes-bio-info.conf

  - name: link this site's conf in sites-enabled
    file: src=/etc/apache2/sites-available/udes-bio-info.conf dest=/etc/apache2/sites-enabled/udes-bio-info.conf owner=root group=root state=link
    notify: restart apache

